R CMD check results: 1 Error, 1 Warning, 1 Note
Empty commit to report what I see:

```
-- R CMD check results ----------------------------- r2dii.match 0.0.0.9000 ----
Duration: 29s

> checking examples ... ERROR
  Running examples in 'r2dii.match-Ex.R' failed
  The error most likely occurred in:

  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: match_all_against_all
  > ### Title: Run matching between two lists
  > ### Aliases: match_all_against_all
  >
  > ### ** Examples
  >
  > library(r2dii.dataraw)
  Loading required package: r2dii.utils
  >
  > loanbook_entities <- loanbook_demo %>%
  +   prepare_loanbook_for_matching()
  >
  > ald_entities <- ald_demo %>%
  +   prepare_ald_for_matching()
  >
  > match_all_against_all(loanbook_entities$simpler_name,
  +              ald_entities$simpler_name)
  Error in map_dfr(.x = names_to_match, .f = match_one_name_against_all,  :
    could not find function "map_dfr"
  Calls: match_all_against_all
  Execution halted

> checking Rd \usage sections ... WARNING
  Documented arguments not in \usage in documentation object 'match_all_against_all':
    'threshold'

  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter 'Writing R documentation files' in the 'Writing R
  Extensions' manual.

> checking R code for possible problems ... NOTE
  match_all_against_all: no visible global function definition for
    'map_dfr'
  match_one_name_against_all: no visible binding for global variable
    'score'
  Undefined global functions or variables:
    map_dfr score

1 error x | 1 warning x | 1 note x
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.

```