FIXME vctrs or tidyr: Can't combine spec_tbl_df
Avoid
Error: Can't combine `..1` <spec_tbl_df<>> and `..2` <tbl_df<>>.
with vctrs 0.2.99.9011 (which dplyr 1 requires).

See reprex at
https://community.rstudio.com/t/cant-combine-1-spec-tbl-df-and-2-tbl-df/60505